# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firmament.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x66irmament.proto\x12\tfirmament"\x1c\n\x07\x43ontent\x12\x11\n\tsha256sum\x18\x01 \x01(\t"7\n\x0f\x43ontentDatabase\x12$\n\x08\x63ontents\x18\x01 \x03(\x0b\x32\x12.firmament.Content"I\n\x0b\x46ileVersion\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\r\n\x05mtime\x18\x03 \x01(\x04\x12\x0c\n\x04size\x18\x04 \x01(\x04"D\n\x13\x46ileVersionDatabase\x12-\n\rfile_versions\x18\x01 \x03(\x0b\x32\x16.firmament.FileVersionb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "firmament_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _CONTENT._serialized_start = 30
    _CONTENT._serialized_end = 58
    _CONTENTDATABASE._serialized_start = 60
    _CONTENTDATABASE._serialized_end = 115
    _FILEVERSION._serialized_start = 117
    _FILEVERSION._serialized_end = 190
    _FILEVERSIONDATABASE._serialized_start = 192
    _FILEVERSIONDATABASE._serialized_end = 260
# @@protoc_insertion_point(module_scope)
