import subprocess
import tempfile
from collections.abc import Generator
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from firmament.config import Config


class RClone:
    """
    Rclone interfacing class.
    """

    def __init__(self, config: "Config"):
        self.config = config

    def run_command(
        self,
        args: list[str],
        filter_text: str | None = None,
        request_combined: bool = False,
        capture_output: bool = False,
    ) -> str | None:
        """
        Wraps running an rclone command with some files that need writing.
        """
        with tempfile.TemporaryDirectory(prefix="firmament-rclone-") as tmpdir:
            # Create rclone config
            config_path = Path(tmpdir) / "rclone.conf"
            self.generate_rclone_config(config_path)
            args += ["--config", str(config_path)]
            # Create combined destination if asked
            if request_combined:
                combined_path = str(Path(tmpdir) / "combined-output")
                args += ["--combined", combined_path]
            # Create filter file if requested
            if filter_text:
                filter_path = Path(tmpdir) / "filters"
                with open(filter_path, "w") as fh:
                    fh.write(filter_text)
                # print("\033[0;36m", filter_text, "\033[0m")
                args += ["--filter-from", str(filter_path)]
            # print(f"== {args} ==")
            if capture_output:
                return subprocess.check_output(
                    ["rclone"] + args, env={"LANG": "en_US.UTF-8"}
                ).decode("utf8")
            else:
                subprocess.check_call(["rclone"] + args, env={"LANG": "en_US.UTF-8"})
            if request_combined:
                return open(combined_path).read()
        return None

    def get_all_files(self, remote: str, path: str = "/") -> Generator[dict]:
        """
        Yields limited file information for the remote (path and size)
        """
        with tempfile.TemporaryDirectory(prefix="firmament-rclone-") as tmpdir:
            config_path = Path(tmpdir) / "rclone.conf"
            self.generate_rclone_config(config_path)
            proc = subprocess.Popen(
                [
                    "rclone",
                    "lsf",
                    "-R",
                    "--format",
                    "sp",
                    f"{remote}:{path}",
                    "--config",
                    str(config_path),
                ],
                stdout=subprocess.PIPE,
                env={"LANG": "en_US.UTF-8"},
                text=True,
            )
            assert proc.stdout is not None
            for line in proc.stdout:
                line = line.rstrip("\n")
                if not line:
                    continue
                size_str, file_path = line.split(";", 1)
                yield {"Path": file_path, "Size": int(size_str)}
            proc.wait()
            if proc.returncode != 0:
                raise subprocess.CalledProcessError(proc.returncode, "rclone")

    def generate_rclone_config(self, target: Path):
        """
        Writes the rclone config file.
        """
        with open(target, "w") as fh:
            fh.write("# Autogenerated file\n")
            for name, remote_config in self.config.config_data.remotes.items():
                fh.write(f"[{name}]\n")
                for key, value in remote_config.items():
                    fh.write(f"{key} = {value}\n")
                fh.write("\n")
