import subprocess
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from firmament.config import Config


class RClone:
    """
    Rclone interfacing class.
    """

    def __init__(self, config: "Config"):
        self.config = config

    def run_command(
        self,
        args: list[str],
        filter_text: str | None = None,
        request_combined: bool = False,
    ):
        """
        Wraps running an rclone command with some files that need writing.
        """
        with tempfile.TemporaryDirectory(prefix="firmament-rclone-") as tmpdir:
            # Create rclone config
            config_path = Path(tmpdir) / "rclone.conf"
            self.generate_rclone_config(config_path)
            args += ["--config", str(config_path)]
            # Create combined destination if asked
            if request_combined:
                combined_path = str(Path(tmpdir) / "combined-output")
                args += ["--combined", combined_path]
            # Create filter file if requested
            if filter_text:
                filter_path = Path(tmpdir) / "filters"
                with open(filter_path, "w") as fh:
                    fh.write(filter_text)
                print("\033[0;36m", filter_text, "\033[0m")
                args += ["--filter-from", str(filter_path)]
            print(f"== {args} ==")
            subprocess.check_call(["rclone"] + args, env={"LANG": "en_US.UTF-8"})

            if request_combined:
                print(open(combined_path).read())

    def generate_rclone_config(self, target: Path):
        """
        Writes the rclone config file.
        """
        with open(target, "w") as fh:
            fh.write("# Autogenerated file\n")
            for name, remote_config in self.config.config_data.remotes.items():
                fh.write(f"[{name}]\n")
                for key, value in remote_config.items():
                    fh.write(f"{key} = {value}\n")
                fh.write("\n")
